config/routes.rb
Rails.application.routes.draw do

  # ルーティングはファイルの上から記載順にマッチする。
  # deviseコントローラーを継承してカスタマイズ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # menberメッソドによりユーザーidが含まれるURLを作成
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'

  # 検索機能
  get 'search', to: 'search#search'

  get 'home/about', to: 'home#about'

  get 'chat/:id', to: 'chat#show', as: 'chat'

end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #belongs_to :user
  #belongs_to :book
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController

  def create
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: params[:book_id])
    favorite.save
  end

  def destroy
    @book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: params[:book_id])
    favorite.destroy
  end

end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if book.favorited_by?(current_user) %>

<%= link_to book_favorites_path(book), method: :delete, remote: true do %>
<i class="fa fa-heart" aria-hidden="true" style="color: red;"></i>
<%= book.favorites.count %>
<% end %>

<% else %>
<%= link_to book_favorites_path(book), method: :post, remote: true do %>
<i class="fa fa-heart-o" aria-hidden="true"></i>
<%= book.favorites.count %>
<% end %>

<% end %>

app/views/favorites/create.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");

app/views/favorites/destroy.js.erb
$('#favorites_buttons_<%= @book.id %>').html("<%= j(render partial: 'favorites/favorite', locals: {book: @book}) %>");