config/routes.rb
Rails.application.routes.draw do

  # ルーティングはファイルの上から記載順にマッチする。
  # deviseコントローラーを継承してカスタマイズ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # menberメッソドによりユーザーidが含まれるURLを作成
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'

  # 検索機能
  get 'search', to: 'search#search'

  get 'home/about', to: 'home#about'

  get 'chat/:id', to: 'chat#show', as: 'chat'

end

app/models/user.rb
class User < ApplicationRecord
  include JpPrefecture
  jp_prefecture :prefecture_code

  # モデル登録時にgeocoderにより、緯度・軽度のデータを登録される。
  geocoded_by :address
  after_validation :geocode

  def address
    address_city + address_street
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable,:validatable
  # 各modelとの関連付け（アソシエーション）
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # throughオプションでユーザーがいいねしているbookを取得
  has_many :favorite_books, through: :favorites
  attachment :profile_image

  has_many :relationships
  # source: :followにてrelationshipsテーブルのfollow_idを参考にしてfollowinsモデルにアクセス
  has_many :followings, through: :relationships, source: :follow
  # foreign_key: 'follow_id'にてfollow_idを入り口としてrelaitionshipsテーブルにアクセスする（入り口）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # source: :userで出口をuser_idにする。userテーブルから自分をフォローしているuserを取ってくる
  has_many :followers, through: :reverse_of_relationships, source: :user

  # １対１のチャット機能関連づけ
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms


  # 住所自動入力
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # userモデルにフォロー機能のメッソドを記載
  def follow(other_user)
    # フォローしようとしているother_userが自分自身ではないか検証
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  # フォローがあればアンフォローを行う
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # self.followingsによりフォローしているUser達を取得。include?(other_user)によりother_userが含まれていないか確認
  def following?(other_user)
    self.followings.include?(other_user)
  end

  # 検索機能
  # self.はUser.を意味する
  def self.search(method,word)
    if method == "forward_match"
      @users = User.where("name LIKE ?","#{word}%")
    elsif method == "backward_match"
      @users = User.where("name LIKE ?","%#{word}")
    elsif method == "perfect_match"
      @users = User.where("name LIKE ?","#{word}")
    elsif method == "partial_match"
      @users = User.where("name LIKE ?","%#{word}%")
    end
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
# 各アクションをオーバーライド
def cansel
  super
end

def create
  super
  ThanksMailer.registration_confirmation(resource).deliver unless resource.invalid?
end

def new
  super
end

def edit
  super
end

def update
  super
end

def destroy
  super
end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  # followingページとfollowerページを表示する定義
  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end

end

app/helpers/users/registrations_helper.rb
module Users::RegistrationsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_profile.html.erb
<table class="table">
	<tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>

	<tr>
		<th>name</th>
		<th><%= user.name %></th>
	</tr>

	<tr>
		<th>introduction</th>
		<th><%= user.introduction %></th>
	</tr>

	<!-- フォロー機能 -->
	<tr>
		<th>follows</th>
		<th>
			<a href="<%= following_user_path(user) %>">
				<%= user.followings.count %></a>
			</th>
		</tr>

		<tr>
			<th>followers</th>
			<th>
				<a href="<%= followers_user_path(user) %>">
					<%= user.followers.count %></a>
				</th>
			</tr>



		</table>

		<div class="row">
			<% if current_user == user %>
			<%= link_to '',edit_user_path(user), class: "col-xs-12 btn btn-default glyphicon glyphicon-wrench edit_user_#{user.id}" %>

			<% else %>
			<% if current_user.following?(user) %>
			<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
			<% end %>
			<% else %>
			<%= form_for(current_user.relationships.build) do |f| %>
			<%= hidden_field_tag :follow_id, user.id %>
			<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
			<% end %>
			<% end %>
						<% if current_user != user %>
			<%= link_to 'チャットを始める', chat_path(user.id) %>
			<% end %>
			<% end %>
			<!-- フォロー機能 -->

		</div>

app/views/users/edit.html.erb
<h2>User info</h2>

<%= form_for(@user) do |f| %>

<!-- エラーメッセージ表示-->
<% if @user.errors.any? %>
	<h3><%= @user.errors.count %>error occurrence</h3><!--エラーメッセ-->
	<ul>
		<% @user.errors.full_messages.each do |message| %>
		<li><%= message %></li>
		<% end %>
	</ul>
<% end %>
<!-- エラーメッセージ表示-->

<div class="field">
	<%= f.label :name %>
	<%= f.text_field :name, class: "name" %>
</div>

<div class="field">
	<%= f.label :image %>
	<%= f.attachment_field :profile_image, class: "user_image" %>
</div>

<div class="field">
	<%= f.label :introduction %>
	<%= f.text_area :introduction, class: "introduction" %>
</div>

<div class="actions">
	<%= f.submit %>
</div>

<% end %>

app/views/users/index.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: current_user %>
		<!--メモ　右側の指定に注意。そこを間違えるとエラーが発生して表示されない -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Users</h2>
		<!--users一覧 -->
		<table class="table">
			<thead>
				<tr>
					<th>image</th>
					<th>name</th>
					<th colspan="4"></th>
				</tr>
			</thead>

			<tbody>
				<% @users.each do |user| %>
				<tr>
					<td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
					<td><%= user.name%></td>

					<!-- フォロー機能 -->
					<td>フォロー数：
						<a href="<%= following_user_path(user) %>">
							<%= user.followings.count %></a>
						</td>

						<td>フォロワー数：
						<a href="<%= followers_user_path(user) %>">
							<%= user.followers.count %></a>
						</td>

						<td>
							<% unless current_user == user %>
							<% if current_user.following?(user) %>
							<%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
							<% end %>
							<% else %>
							<%= form_for(current_user.relationships.build) do |f| %>
							<%= hidden_field_tag :follow_id, user.id %>
							<%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
							<% end %>
							<% end %>
							<% end %>
						</td>
						<!-- フォロー機能 -->

						<td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
					</tr>
					<% end %>
				</tbody>
			</table>
			<!--users一覧 -->

		</div>
	</div>

app/views/users/show.html.erb
<div class="row">
	<div class="col-xs-3">

		<h2>User info</h2>
		<%= render 'users/profile', user: @user %>
		<!--同コントローラーのviewで表示ならusersは省略可 -->

		<h2>New book</h2>
		<%= render 'books/newform', book: @book %>

	</div>

	<div class="col-xs-9">
		<h2>Books</h2>
		<!--books一覧 -->
		<table class="table table-hover table-inverse">
			<thead>
				<tr>
					<th></th>
					<th>Title</th>
					<th>Opinion</th>
					<th colspan="3"></th>
				</tr>
			</thead>

			<tbody>
				<% @books.each do |book| %>
				<tr>
					<td>
						<%= link_to (book.user) do %>
						<%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %>
						<% end %>
					</td>
					<td><%= link_to book.title,book, class: "book_#{book.id}" %></td>
					<td><%= book.body %></td>

					<!-- いいね機能（非同期） -->
					<td id="favorites_buttons_<%= book.id %>">
						<%= render partial: 'favorites/favorite', locals: { book: book} %>
					</td>
					<!-- いいね機能（非同期） -->

					<td>コメント数：
						<%= link_to book.book_comments.count, book %></a>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
		<!--books一覧 -->

	</div>
</div>

<% if @user == current_user %>
<h2>gmap</h2>

<div id='map'>
</div>

<style>
  #map{
    height: 400px;
  }
</style>

<script type="text/javascript">
  function initMap() {

    var test = {lat: <%= @user.latitude %>, lng: <%= @user.longitude %>};
    var map = new google.maps.Map(document.getElementById('map'), {
      zoom: 15,
      center: test
    });
    var transitLayer = new google.maps.TransitLayer();
    transitLayer.setMap(map);

    var contentString = '住所：<%= @user.address %>';
    var infowindow = new google.maps.InfoWindow({
      content: contentString
    });

    var marker = new google.maps.Marker({
      position:test,
      map: map,
      title: contentString
    });

    marker.addListener('click', function() {
      infowindow.open(map, marker);
    });
  }
</script>
<script async defer
src="https://maps.googleapis.com/maps/api/js?key=<%= ENV['GMAP_API_KEY'] %>&callback=initMap">
</script>
<% end %>

app/views/users/show_follow.html.erb
<h2>Follow Users</h2>


  <div class="col-xs-12">

    <!--users一覧 -->
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name%></td>

          <!-- フォロー機能 -->
          <td>フォロー数：
            <a href="<%= following_user_path(user) %>">
              <%= user.followings.count %></a>
            </td>

            <td>フォロワー数：
            <a href="<%= followers_user_path(user) %>">
              <%= user.followers.count %></a>
            </td>

            <td>
              <% unless current_user == user %>
              <% if current_user.following?(user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
              <% end %>
              <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
              <% end %>
              <% end %>
              <% end %>
            </td>
            <!-- フォロー機能 -->

            <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>

app/views/users/show_follower.html.erb
<h2>Follower Users</h2>


  <div class="col-xs-12">

    <!--users一覧 -->
    <table class="table">
      <thead>
        <tr>
          <th>image</th>
          <th>name</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @users.each do |user| %>
        <tr>
          <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-mini.jpg") %></td>
          <td><%= user.name%></td>

          <!-- フォロー機能 -->
          <td>フォロー数：
            <a href="<%= following_user_path(user) %>">
              <%= user.followings.count %></a>
            </td>

            <td>フォロワー数：
            <a href="<%= followers_user_path(user) %>">
              <%= user.followers.count %></a>
            </td>

            <td>
              <% unless current_user == user %>
              <% if current_user.following?(user) %>
              <%= form_for(current_user.relationships.find_by(follow_id: user.id), html: { method: :delete }) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'Unfollow', class: 'btn btn-danger btn-block' %>
              <% end %>
              <% else %>
              <%= form_for(current_user.relationships.build) do |f| %>
              <%= hidden_field_tag :follow_id, user.id %>
              <%= f.submit 'Follow', class: 'btn btn-primary btn-block' %>
              <% end %>
              <% end %>
              <% end %>
            </td>
            <!-- フォロー機能 -->

            <td><%= link_to "Show", user, class: "user_#{user.id}" %></td>
          </tr>
          <% end %>
        </tbody>
      </table>