config/routes.rb
Rails.application.routes.draw do

  # ルーティングはファイルの上から記載順にマッチする。
  # deviseコントローラーを継承してカスタマイズ
  devise_for :users, :controllers => {
    :registrations => "users/registrations"
  }

  # menberメッソドによりユーザーidが含まれるURLを作成
  resources :users,only: [:show,:index,:edit,:update] do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: [:create, :destroy]

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
  end

  root 'home#top'

  # 検索機能
  get 'search', to: 'search#search'

  get 'home/about', to: 'home#about'

  get 'chat/:id', to: 'chat#show', as: 'chat'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  # userモデルに従属する
  belongs_to :user
  # 1件のbookに対して複数のいいねの関係
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # throughオプションでbookが誰にいいねされているのかを取得
  has_many :favorite_users, through: :favorites

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # 検索機能
  # self.はBook.を意味する
  def self.search(method,word)
    if method == "forward_match"
      @books = Book.where("title LIKE ?","#{word}%")
    elsif method == "backward_match"
      @books = Book.where("title LIKE ?","%#{word}")
    elsif method == "perfect_match"
      @books = Book.where("title LIKE ?","#{word}")
    elsif method == "partial_match"
      @books = Book.where("title LIKE ?","%#{word}%")
    end
  end

	#バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
	#presence trueは空欄の場合を意味する。
	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}
end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book

  validates :comment, presence: true
end

app/models/chat.rb
class Chat < ApplicationRecord

  belongs_to :user
  belongs_to :room
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  #belongs_to :user
  #belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :user

  # class_name: 'User'でfollowモデルが存在せずにuserモデルにbelongs_toするよう明示
  belongs_to :follow, class_name: 'User'

  # どちらか一つでもなかった場合保存されないようにvalidationを設定する
  validates :user_id, presence: true
  validates :follow_id, presence: true

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :chats
  has_many :user_rooms

end

app/models/user.rb
class User < ApplicationRecord
  include JpPrefecture
  jp_prefecture :prefecture_code

  # モデル登録時にgeocoderにより、緯度・軽度のデータを登録される。
  geocoded_by :address
  after_validation :geocode

  def address
    address_city + address_street
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :trackable,:validatable
  # 各modelとの関連付け（アソシエーション）
  has_many :books, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :book_comments, dependent: :destroy

  # throughオプションでユーザーがいいねしているbookを取得
  has_many :favorite_books, through: :favorites
  attachment :profile_image

  has_many :relationships
  # source: :followにてrelationshipsテーブルのfollow_idを参考にしてfollowinsモデルにアクセス
  has_many :followings, through: :relationships, source: :follow
  # foreign_key: 'follow_id'にてfollow_idを入り口としてrelaitionshipsテーブルにアクセスする（入り口）
  has_many :reverse_of_relationships, class_name: 'Relationship', foreign_key: 'follow_id'
  # source: :userで出口をuser_idにする。userテーブルから自分をフォローしているuserを取ってくる
  has_many :followers, through: :reverse_of_relationships, source: :user

  # １対１のチャット機能関連づけ
  has_many :user_rooms
  has_many :chats
  has_many :rooms, through: :user_rooms


  # 住所自動入力
  def prefecture_name
    JpPrefecture::Prefecture.find(code: prefecture_code).try(:name)
  end

  def prefecture_name=(prefecture_name)
    self.prefecture_code = JpPrefecture::Prefecture.find(name: prefecture_name).code
  end

  # userモデルにフォロー機能のメッソドを記載
  def follow(other_user)
    # フォローしようとしているother_userが自分自身ではないか検証
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  # フォローがあればアンフォローを行う
  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end

  # self.followingsによりフォローしているUser達を取得。include?(other_user)によりother_userが含まれていないか確認
  def following?(other_user)
    self.followings.include?(other_user)
  end

  # 検索機能
  # self.はUser.を意味する
  def self.search(method,word)
    if method == "forward_match"
      @users = User.where("name LIKE ?","#{word}%")
    elsif method == "backward_match"
      @users = User.where("name LIKE ?","%#{word}")
    elsif method == "perfect_match"
      @users = User.where("name LIKE ?","#{word}")
    elsif method == "partial_match"
      @users = User.where("name LIKE ?","%#{word}%")
    end
  end

  #バリデーションは該当するモデルに設定する。エラーにする条件を設定できる。
  validates :name, length: {maximum: 20, minimum: 2}
  validates :introduction, length: { maximum: 50 }
end

app/models/user_room.rb
class UserRoom < ApplicationRecord
  belongs_to :user
  belongs_to :room
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :authenticate_user!
  before_action :correct_user, only: [:edit, :update]

  def show
  	@book = Book.find(params[:id])
    @book_new = Book.new
    @comment = BookComment.new
    @comments = @book.book_comments
    @user = @book.user
  end

  def index
  	@books = Book.all #一覧表示するためにBookモデルの情報を全てくださいのall
    @book = Book.new
  end

  def create
  	@book = Book.new(book_params) #Bookモデルのテーブルを使用しているのでbookコントローラで保存する。
    @book.user_id = current_user.id
  	if @book.save #入力されたデータをdbに保存する。
  		redirect_to @book, notice: "successfully created book!"#保存された場合の移動先を指定。
  	else
  		@books = Book.all
  		render 'index'
  	end
  end

  def edit
  	@book = Book.find(params[:id])
  end



  def update
  	@book = Book.find(params[:id])
  	if @book.update(book_params)
  		redirect_to @book, notice: "successfully updated book!"
  	else #if文でエラー発生時と正常時のリンク先を枝分かれにしている。
  		render "edit"
  	end
  end

  def destroy
  	@book = Book.find(params[:id])
  	@book.destroy
  	redirect_to books_path, notice: "successfully delete book!"
  end

  private

  def book_params
  	params.require(:book).permit(:title, :body)
  end

  def correct_user
    book = Book.find(params[:id])
    if current_user.id != book.user.id
      redirect_to books_path
    end
  end

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController
   before_action :authenticate_user!

  def show
    @user = User.find(params[:id])
    rooms = current_user.user_rooms.pluck(:room_id)
    user_rooms = UserRoom.find_by(user_id: @user.id, room_id: rooms)

    unless user_rooms.nil?
      @room = user_rooms.room
    else
      @room = Room.new
      @room.save
      UserRoom.create(user_id: current_user.id, room_id: @room.id)
      UserRoom.create(user_id: @user.id, room_id: @room.id)
    end
    @chats = @room.chats
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def top
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :baria_user, only: [:edit, :update]

  def show
  	@user = User.find(params[:id])
  	@books = @user.books
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def index
  	@users = User.all #一覧表示するためにUserモデルのデータを全て変数に入れて取り出す。
  	@book = Book.new #new bookの新規投稿で必要（保存処理はbookコントローラー側で実施）
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
  	@user = User.find(params[:id])
  	if @user.update(user_params)
  		redirect_to user_path(@user.id), notice: "successfully updated user!"
  	else
  		render "edit"
  	end
  end

  # followingページとfollowerページを表示する定義
  def following
    @user = User.find(params[:id])
    @users = @user.followings
    render 'show_follow'
  end

  def followers
    @user = User.find(params[:id])
    @users = @user.followers
    render 'show_follower'
  end

  private
  def user_params
  	params.require(:user).permit(:name, :introduction, :profile_image)
  end

  #url直接防止　メソッドを自己定義してbefore_actionで発動。
  def baria_user
  	unless params[:id].to_i == current_user.id
  		redirect_to user_path(current_user)
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Bookers2</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <!--ヘッダーの記述-->
  <header class="navbar navbar-fixed-top navbar-inverse">
    <div class="container">

      <nav class="nav navbar-nav navbar-left">
        <span>Bookers</span>
      </nav>
      <nav>
        <ul class="nav navbar-nav navbar-right">
          <!--if文でサインインとアウト時の表示を変更-->
          <% if user_signed_in? %>
          <li><%= link_to ' home', user_path(current_user), class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' users', users_path, class: 'glyphicon glyphicon-user users' %></li>
          <li><%= link_to ' books', books_path, class: 'glyphicon glyphicon-book books' %></li>
          <li><%= link_to ' logout', destroy_user_session_path, method: :delete, class: 'glyphicon glyphicon-log-out logout' %></li>
          <% else %>
          <li><%= link_to ' home', root_path, class: 'glyphicon glyphicon-home home' %></li>
          <li><%= link_to ' about', home_about_path, class: 'glyphicon glyphicon-link about' %></li>
          <li><%= link_to ' sign up', new_user_registration_path, class: 'glyphicon glyphicon-edit sign_up' %></li>
          <li><%= link_to ' login', new_user_session_path, class: 'glyphicon glyphicon-log-in sign_in' %></li>
          <% end %>
        </ul>
      </nav>

    </div>
  </header>
  <!--ヘッダーの記述-->
  <% if user_signed_in? %>
  <div class="search-form" style="margin-top: 70px; text-align: center;">
    <!-- 検索機能 -->
    <%= form_tag(search_path, method: :get ) do %>
    <%= text_field(@search_content, :search_word ) %>
    <%= select(@search_content, :search_select, [["user", "user_search"],["book", "book_search"]]) %>
    <%= select(@search_content, :search_method, [["前方一致", "forward_match"],["後方一致", "backward_match"],["完全一致", "perfect_match"],["部分一致", "partial_match"]]) %>
    <%= submit_tag 'Search', name: :nil %>
    <% end %>
  </div>
  <% end %>

  <div class="container">
    <p></p>
    <p id="notice"><%= flash[:notice] %></p> <!--デバイスでnotice設定されているので呼び出してるだけ-->
    <%= yield %>
  </div>
</body>
</html>